project:
  type: website
  output-dir: docs

website:
  title: "Statistical Rethinking colearning 2023"

  sidebar:
    contents:
      - href: index.qmd
        text: Home
      - section: "Notes"
        href: notes/00-notes-listing.qmd
        contents:
          - href: notes/01-notes.qmd
            text: Lecture 01
          - href: notes/02-notes.qmd
            text: Lecture 02

format:
  html:
    theme:
      dark: darkly
      light: flatly
    toc: true
